# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: native
    chainName: basecamp
    connections:
      - token: ethereum|sepolia|${DEPLOYED_ADDRESS}
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: ${DEPLOYED_ADDRESS}
    chainName: sepolia
    connections:
      - token: ethereum|basecamp|native
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ether
    standard: EvmHypSynthetic
    symbol: ETH 